Terraform 1
Otus-DevOps-2021-05/leon4eg13ru_infra pull request #6
Opened 2021-07-09 15:35 UTC by leon4eg13ru

# Выполнено ДЗ №

 - [x] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Создан сервис-аккаунт terraform
 - Создан VM согласно описанию
 - Задействованы input переменные

## Как запустить проект:
 - cd terraform && terraform init && terraform apply

## Как проверить работоспособность:
 - Например, перейти по ссылке http://178.154.240.249:9292

## PR checklist
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2021-07-11 18:20 UTC, mrgreyves requested changes
Здравствуйте!) Оставил комментарий к файлу, дз возвращаю на доработку

2021-07-11 18:20 UTC, mrgreyves commented on terraform/main.tf
> +  required_providers {
Локальное тестирование проходит нормально? Ругается на то что не правильно объявлен провайдер, стоит свериться с официальной документацией

2021-07-12 07:21 UTC, leon4eg13ru commented on terraform/main.tf
> +  required_providers {
Проходит нормально, но с версией terraform 1.0.1
Необходимо именно под 0.12 версию затачивать?

2021-07-12 17:14 UTC, mrgreyves commented on terraform/main.tf
> +  required_providers {
Да, в рамках курса используем "не сильно свежую" версию

2021-07-12 17:14 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!)

2021-07-13 08:01 UTC, merged